export const STACK_ICON_MAP: Record<string, string> = {
  React: "logos:react",
  "Next.js": "logos:nextjs-icon",
  "Tailwind CSS": "logos:tailwindcss-icon",
  "Shadcn UI": "simple-icons:shadcnui",
  "Material UI": "logos:material-ui",
  "Radix UI": "simple-icons:radixui",
  NestJS: "logos:nestjs",
  "Node.js": "logos:nodejs-icon",
  Express: "simple-icons:express",
  MySQL: "logos:mysql",
  PostgreSQL: "logos:postgresql",
  "JSON Web Tokens": "simple-icons:jsonwebtokens",
  MongoDB: "logos:mongodb-icon",
  Redis: "logos:redis",
  Figma: "logos:figma",
  Github: "logos:github-icon",
  Postman: "logos:postman-icon",
  ChatGPT: "simple-icons:openai",
  Jira: "logos:jira",
  "Github Copilot": "simple-icons:githubcopilot",
  "VS Code": "logos:visual-studio-code",
  Cloudflare: "logos:cloudflare-icon",
};
